apiVersion: v1
kind: Service
metadata:
  name: zimozi-app
  namespace: zimozi
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: zimozi-app
